# satware® RepoInsight Configuration

name: "RepoInsight Project"
root_path: "."  # Current directory
output_path: "docs/repository_documentation.md"

# Directories to scan and exclude
scan_directories:
  - "src"
  - "tests"
exclude_directories:
  - "venv"
  - "node_modules"
  - ".git"
  - "__pycache__"

# File patterns for filtering
file_patterns:
  include:
    - "*.py"
    - "*.md"
    - "*.yaml"
    - "*.yml"
  exclude:
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - "*__pycache__*"
    - "*.git*"

# LLM configuration (Cortex)
llm:
  enabled: true
  provider: "cortex"
  api_base_url: "http://localhost:8000/v1"
  model: "llama3"
  temperature: 0.3
  max_tokens: 500
  timeout: 30
  cache_enabled: true
  system_prompt_template: "Analyze the following {language} code and provide a concise description in markdown format. Focus on the main purpose, key functionality, and important patterns or techniques used. Keep the description under 5 sentences."

# Processing configuration
processing:
  max_concurrent_tasks: 4
  chunk_size: 8192

# Output configuration
output:
  include_toc: true
  include_metadata: true
  include_file_stats: true
  include_commit_info: true
  syntax_highlighting: true

# Cache path for LLM responses
cache_path: ".repoinsight_cache"
